theme: minima
title: EG's blog
author : egiberne
description: About my coding journey.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
minima:
  skin: classic

social_links:
 - title: EG at GitHub
 icon: github
 url: "https://github.com/egiberne"
        
- title: EG at X
 icon: x-twitter
 url: "https://x.com/egiberne_"
